### ISSUE TITLE
Unchecked is ignored in generic type aliases

### ISSUE THREAD

**Issue by oolkhovoy** [ruby/rbs#899] opened 2022-02-07 14:39 UTC
Hi! With following example:
```
class Foo[in A, out B]
end

type foo[unchecked out A, unchecked in B] = Foo[A, B]
```
`rbs validate` return
```
 sig/exp.rbs:4:44...4:53: Type parameter variance error: A is covariant but used as incompatible variance (RBS::InvalidVarianceAnnotationError)
```

**Comment by soutaro** [comment] 2022-02-21 11:05
Thank you @oolkhovoy!

I think the issue is fixed by #909, and the change will ship soon.

**Closed** 2022-02-21 11:04 UTC
Labels: bug
