### ISSUE TITLE
Syntax error when string union with escape

### ISSUE THREAD

**Issue by ksss** [ruby/rbs#996] opened 2022-05-14 13:36 UTC
`"\\"` and `1` can create a Union type.
`"a"` and `"\\"` also can create a Union type,
whereas `"\\"` and `"a"` would result in a Syntax error.

Shouldn't it be possible to create a Union type in `"\\" | "a"` cases?

```rb
$ ruby -r rbs -e 'p RBS::Parser.parse_type(%q{"\\" | 1})'
#<RBS::Types::Union:0x00000001047b2118 @types=[#<RBS::Types::Literal:0x00000001047b22d0 @literal="\\", @location=#<RBS::Location:820 buffer=a.rbs, start=1:0, pos=0...3, children= source='"\"'>>, #<RBS::Types::Literal:0x00000001047b21b8 @literal=1, @location=#<RBS::Location:840 buffer=a.rbs, start=1:6, pos=6...7, children= source='1'>>], @location=#<RBS::Location:860 buffer=a.rbs, start=1:0, pos=0...7, children= source='"\" | 1'>>
```

```rb
$ ruby -r rbs -e 'p RBS::Parser.parse_type(%q{"a" | "\\"})'
#<RBS::Types::Union:0x0000000147162590 @types=[#<RBS::Types::Literal:0x0000000147162b58 @literal="a", @location=#<RBS::Location:820 buffer=a.rbs, start=1:0, pos=0...3, children= source='"a"'>>, #<RBS::Types::Literal:0x0000000147162720 @literal="\\", @location=#<RBS::Location:840 buffer=a.rbs, start=1:6, pos=6...9, children= source='"\"'>>], @location=#<RBS::Location:860 buffer=a.rbs, start=1:0, pos=0...9, children= source='"a" | "\"'>>
```

```rb
$ ruby -r rbs -e 'p RBS::Parser.parse_type(%q{"\\" | "a"})'
/Users/ksss/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/rbs-2.4.0/lib/rbs/parser_aux.rb:4:in `_parse_type': a.rbs:1:7...1:8: Syntax error: expected a token `pEOF`, token=`a` (tLIDENT) (RBS::ParsingError)
	from /Users/ksss/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/rbs-2.4.0/lib/rbs/parser_aux.rb:4:in `parse_type'
	from -e:1:in `<main>'
```

```
$ ruby -v
ruby 3.1.1p18 (2022-02-18 revision 53f5fc4236) [arm64-darwin21]
$ rbs -v
rbs 2.4.0
```

**Comment by soutaro** [comment] 2022-06-22 05:41
`%q{"\\" | "a"}` is `"\" | "a"` in RBS. So, the syntax error is expected one.

The problem is when we give `"\\" | "a"` in RBS. This should be parse. But, it didn't because of the `dqstring` pattern of `lever.re`

```
      dqstring = ["] ("\\"["] | [^"\x00])* ["];                     // Before
      dqstring = ["] ("\\"[abefnrstv"\\] | [^"\\\x00])* ["];        // After
```

With the _Before_ pattern, the first `\` in `"\\"` was eaten by the second alternation. And the next `\"` in `"\\"` was eaton by the first alternation. It cannot detect the end of string, and parsing fails.

The _After_ pattern is more explicit on what can come just after `\`. The two `\\` are eaten by the first alternation, and the closing `"` is processed correctly.

**Closed** 2022-06-22 06:24 UTC
